// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhycjfjpehrnlmogrwqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoeWNqZmpwZWhybmxtb2dyd3FxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1OTQ4MTcsImV4cCI6MjA3MDE3MDgxN30.QmgHQDDmfUCTOgmKuaCHC76fd6YagrSz_80-3U3tyXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});